/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ImageData {
    contentType: string;
    data: Uint8Array;
}
export interface Debt {
    debtor: User;
    amount: bigint;
    creditor: User;
}
export interface Pact {
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    isActive: boolean;
    currency: string;
}
export interface Bill {
    id: bigint;
    participants: Array<Principal>;
    name: string;
    createdAt: bigint;
    createdBy: Principal;
    isImage: boolean;
    amount: bigint;
}
export interface UserSummary {
    total: bigint;
    participant: User;
    spent: bigint;
    bills: Array<{
        name: string;
        payer: User;
        amount: bigint;
    }>;
    debts: Array<Debt>;
}
export interface User {
    id: Principal;
    username: string;
}
export interface backendInterface {
    addBill(name: string, amount: bigint, participants: Array<Principal>, image: ImageData | null): Promise<Bill>;
    addUser(id: Principal, username: string): Promise<User>;
    addUserSelf(username: string): Promise<void>;
    getAllBills(): Promise<Array<Bill>>;
    getAllUsers(): Promise<Array<User>>;
    getBillById(id: bigint): Promise<Bill>;
    getImageByBillId(id: bigint): Promise<ImageData>;
    getPact(): Promise<Pact>;
    initPact(name: string, currency: string, username: string): Promise<void>;
    removeBillById(id: bigint): Promise<void>;
    settle(): Promise<Pact>;
    summary(): Promise<Array<UserSummary>>;
}
import type { ImageData as _ImageData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBill(arg0: string, arg1: bigint, arg2: Array<Principal>, arg3: ImageData | null): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addUser(arg0: Principal, arg1: string): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1);
            return result;
        }
    }
    async addUserSelf(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserSelf(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserSelf(arg0);
            return result;
        }
    }
    async getAllBills(): Promise<Array<Bill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return result;
        }
    }
    async getAllUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getBillById(arg0: bigint): Promise<Bill> {
        if (this.processError) {
            try {
                const result = await this.actor.getBillById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBillById(arg0);
            return result;
        }
    }
    async getImageByBillId(arg0: bigint): Promise<ImageData> {
        if (this.processError) {
            try {
                const result = await this.actor.getImageByBillId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getImageByBillId(arg0);
            return result;
        }
    }
    async getPact(): Promise<Pact> {
        if (this.processError) {
            try {
                const result = await this.actor.getPact();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPact();
            return result;
        }
    }
    async initPact(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initPact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initPact(arg0, arg1, arg2);
            return result;
        }
    }
    async removeBillById(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBillById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBillById(arg0);
            return result;
        }
    }
    async settle(): Promise<Pact> {
        if (this.processError) {
            try {
                const result = await this.actor.settle();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.settle();
            return result;
        }
    }
    async summary(): Promise<Array<UserSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.summary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.summary();
            return result;
        }
    }
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageData | null): [] | [_ImageData] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
